config/routes.rb
# Rails.application.routes.draw do
#   root 'home#index'

#   resources :nodes
# end

Rails.application.routes.draw do
  root 'taxonomies#index'

  resources :taxonomies do
    resources :nodes
  end

  resources :nodes do
    resources :nodes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ApplicationRecord
  belongs_to :taxonomy, polymorphic: true, optional: true
  belongs_to :node, optional: true

  has_many :nodes, as: :expandable, dependent: :destroy

  validates :title, presence: true
end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
    has_many :nodes, as: :expandable, dependent: :destroy

    validates :title, presence: true
    #validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nodes = Node.all
    @taxonomies = Taxonomy.all
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
before_action :find_expandable

    def new
        @node = Node.new
    end

    def edit
        @node = @expandable.nodes.find(params[:id])
    end
    
    def create
        logger.debug("//////")
        logger.debug(node_params)
        @node = @expandable.nodes.create(node_params)
        if @node.save
            redirect_back fallback_location: root_path, notice: 'Node added!'
        else
            redirect_back fallback_location: root_path, notice: "Error while creating node!"
            logger.debug("----")
            logger.debug(@node.errors.full_messages)
        end
    end

    def update
        @node = Node.find(params[:id])
    
        if @node.update(node_params)
            redirect_back fallback_location: root_path
        else
          render :edit
        end
    end

    def to_json
        {
          :nodes => expandable.nodes.collect { |n| n.to_json }
        }
    end

    def destroy
        @node = Node.find(params[:id])
        @node.destroy
        redirect_back fallback_location: root_path, notice: 'Node added!'
    end

    private
        def node_params
            params.fetch(:node, {}).permit(:title, :body, :taxonomy_id, :node_id, :startDate, :endDate, :kingdom, :phylum, :clades)
        end

        def find_expandable
            @expandable = Node.find_by_id(node_params[:node_id]) if node_params[:node_id]
            @expandable = Taxonomy.find_by_id(node_params[:taxonomy_id]) if node_params[:taxonomy_id]
        end
end

app/controllers/taxonomies_controller.rb
class TaxonomiesController < ApplicationController
  def index
    @taxonomies = Taxonomy.all
  end

  def show
    @taxonomy = Taxonomy.find(params[:id])
  end

  def new
    @taxonomy = Taxonomy.new
  end

  def create
    @taxonomy = Taxonomy.new(taxonomy_params)

    if @taxonomy.save
      redirect_to @taxonomy
    else
      render :new
    end
  end

  def edit
    @taxonomy = Taxonomy.find(params[:id])
  end

  def update
    @taxonomy = Taxonomy.find(params[:id])

    if @taxonomy.update(taxonomy_params)
      redirect_to @taxonomy
    else
      render :edit
    end
  end

  def destroy
    @taxonomy = Taxonomy.find(params[:id])
    @taxonomy.destroy

    redirect_to root_path
  end

  private
    def taxonomy_params
      params.require(:taxonomy).permit(:title, :description, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/taxonomies_helper.rb
module TaxonomiesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<h1>Enter an item below</h1>

<br><br>

<h2>Taxonomies</h2>
<div class="row">
    <ol>
    <% @taxonomies.each do |taxonomy| %>
        <a href='<%= article_path(article) %>'>
            <li>
                <%= taxonomy.title %>
                <%= link_to 'hi', taxonomy, method: :delete, data: {confirm: 'Are you sure you want to delete ' + taxonomy.title + '?'}, class: 'btn btn-primary' %>
            </li>
        </a>
    <% end %>
    </ol>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Taxonomy Title</h2>
        <hr>

        <% flash.each do |type, msg| %>
            <%= content_tag :div, msg, class: 'alert alert-' + type %>
        <% end %>

        <ol>
        <% @nodes.each do |node| %>
            <h3>
                <li>
                    <%= node.title %>
                    <%= link_to 'hi', node, method: :delete, data: {confirm: 'Are you sure you want to delete ' + node.title + '?'}, class: 'btn btn-primary' %>
                </li>
            </h3>
        <% end %>
        </ol>
    </div>

    <div class="col-md-6">
        <h3>Enter Node Information</h3>
        <%= form_with scope: :node, url: nodes_path do |f| %>
            <%= f.text_field :title, placeholder: "Type node title" %>
            <br><br>
            <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taxinomia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/nodes/_node.html.erb
<div class="node-base">
    <p>
        <strong><%= node.title %></strong>
    </p>

    <p onclick="ToggleDetails(<%= node.id %>)"><em>Description</em>: <%= node.body %></p>

    <div class="details-container" id="details-container-<%= node.id %>">
        <p><em>First Appearance</em>: <%= node.startDate %></p>
        <p><em>Last Appearance</em>: <%= node.endDate %></p>
        <p><em>Kingdom</em>: <%= node.kingdom %></p>
        <p><em>Phylum</em>: <%= node.phylum %></p>
        <p><em>Clades</em>: <%= node.clades %></p>
        <p><em>type</em>: <%= node.expandable_type %></p>
        <p><em>eid</em>: <%= node.expandable_id %></p>
        <p><em>nid</em>: <%= node.id %></p>
    </div>

    <div class="node-buttons" id="node-buttons-<%= node.id %>">
        <button class="btn btn-primary" onclick="ToggleEditNodeForm(<%= node.id %>)">✎ Edit Node</button>
        <button class="btn btn-info" onclick="ToggleAddChildForm(<%= node.id %>)">＋ Add Child Node</button>
        <% @node = node %>
        <%= link_to 'Delete Node', node_path(node.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>

    <div class="edit-node-form-container" id="edit-node-form-container-<%= node.id %>">
        <%= form_with model: [node] do |form| %>
        <p>
            <%= form.label :title %><br>
            <%= form.text_field :title %>
        </p>
        <p>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
        </p>
        <p>
            <%= form.label "First Appearance" %><br>
            <%= form.text_field :startDate %>
        </p>
        <p>
            <%= form.label "Last Appearance" %><br>
            <%= form.text_field :endDate %>
        </p>
        <p>
            <%= form.label "Kingdom" %><br>
            <%= form.text_field :kingdom %>
        </p>
        <p>
            <%= form.label "Phylum" %><br>
            <%= form.text_field :phylum %>
        </p>
        <p>
            <%= form.label "Clades" %><br>
            <%= form.text_field :clades %>
        </p>
        <%= form.hidden_field :taxonomy_id, :value => @taxonomy.id %>
        <p>
            <%= form.submit class: "btn btn-primary" %>
        </p>
        <% end %>
    </div>

    <div class="div-base add-child-form-container" id="add-child-form-container-<%= node.id %>">
        <%= form_with model: [node, Node.new] do |form| %>
        <p>
            <%= form.label :title %><br>
            <%= form.text_field :title %>
        </p>
        <p>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
        </p>
        <p>
            <%= form.label "First Appearance" %><br>
            <%= form.text_field :startDate %>
        </p>
        <p>
            <%= form.label "Last Appearance" %><br>
            <%= form.text_field :endDate %>
        </p>
        <p>
            <%= form.label "Kingdom" %><br>
            <%= form.text_field :kingdom %>
        </p>
        <p>
            <%= form.label "Phylum" %><br>
            <%= form.text_field :phylum %>
        </p>
        <p>
            <%= form.label "Clades" %><br>
            <%= form.text_field :clades %>
        </p>
        <%= form.hidden_field :node_id, :value => node.id %>
        <p>
            <%= form.submit class: "btn btn-primary" %>
        </p>
        <% end %>
    </div>

    <div class="node-children-container" id="node-children-container-<%= node.id %>">
        <%= render partial: 'nodes/node', collection: node.nodes %>
    </div>
</div>

app/views/taxonomies/_form.html.erb
<div class="container" id="new-taxonomy-container">
  <%= form_with model: taxonomy do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>

      <% taxonomy.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %>

      <% taxonomy.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :author %><br>
      <%= form.text_field :author, placeholder: "Anonymous" %>

      <% taxonomy.errors.full_messages_for(:author).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/taxonomies/edit.html.erb
<h1>Edit Taxonomy</h1>

<%= render "form", taxonomy: @taxonomy%>

app/views/taxonomies/index.html.erb
<div class="container" id="site-hero">
    <h1>Taxonomia</h1>
    <h2>Crowdsourced Classification.</h2>
</div>

<%= link_to "New Taxonomy", new_taxonomy_path, class: "btn btn-success", id: "new-taxonomy-btn" %>

<div class="container" id="recent-taxonomies-container">
    <h2>Recent Taxonomies</h2>
    <div class="row">
        <% @taxonomies.last(20).each do |taxonomy| %>
            <a href='<%= taxonomy_path(taxonomy) %>' class="recent-taxonomy-link">
                    <%= taxonomy.title %>
            </a>
        <% end %>
    </div>
</div>

<div class="container navbar-fixed-bottom">
    <div class="navbar ">
        <ul class="nav" id="main-nav">
            <li><a href="https://devpost.com/software/taxonomia">About</a></li>
            <li><a href="https://github.com/SKaplanOfficial/Taxonomia">GitHub</a></li>
        </ul>
    </div>
</div>

app/views/taxonomies/new.html.erb
<div class="navbar ">
    <div class="navbar-inner">
        <div class="container">
            <ul class="nav" id="main-nav">
                <li><a href="/">Home</a></li>
                <li><a href="https://devpost.com/software/taxonomia">About</a></li>
                <li><a href="https://github.com/SKaplanOfficial/Taxonomia">GitHub</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="container page-hero">
    <h1>New Taxonomy</h1>
</div>

<%= render "form", taxonomy: @taxonomy%>

app/views/taxonomies/show.html.erb
<div class="navbar ">
    <div class="navbar-inner">
        <div class="container">
            <ul class="nav" id="main-nav">
                <li><a href="/">Home</a></li>
                <li><a href="https://devpost.com/software/taxonomia">About</a></li>
                <li><a href="https://github.com/SKaplanOfficial/Taxonomia">GitHub</a></li>
            </ul>
        </div>
    </div>
</div>

<div id="taxonomy-header">
  <h1><%= @taxonomy.title %></h1>

  <p class="taxonomy-desc"><em>Description</em>: <%= @taxonomy.description %></p>

  <p class="taxonomy-author"><em>Created By</em>: <%= @taxonomy.author %></p>

  <%= link_to "⚙ Taxonomy Settings", edit_taxonomy_path(@taxonomy), class: "btn btn-primary" %>
  <button class="btn btn-info" onclick="ToggleTLNodeForm()">＋ Add Top-Level Node</button>
  <%= link_to "× Delete", taxonomy_path(@taxonomy), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
</div>

<% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: 'alert alert-' + type %>
<% end %>

<div class="div-base" id="tl-node-form-container">
  <h2>Add Node</h2>
  <%= form_with model: [ @taxonomy, Node.new ] do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.label "First Appearance" %><br>
      <%= form.text_field :startDate %>
    </p>
    <p>
      <%= form.label "Last Appearance" %><br>
      <%= form.text_field :endDate %>
    </p>
    <p>
      <%= form.label "Kingdom" %><br>
      <%= form.text_field :kingdom %>
    </p>
    <p>
      <%= form.label "Phylum" %><br>
      <%= form.text_field :phylum %>
    </p>
    <p>
      <%= form.label "Clades" %><br>
      <%= form.text_field :clades %>
    </p>
    <%= form.hidden_field :taxonomy_id, :value => @taxonomy.id %>
    <p>
      <%= form.submit class: "btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= render partial: 'nodes/node', collection: @taxonomy.nodes %>